<a href="https://colab.research.google.com/github/Radhi1999/radhika_INFO5731_Fall2022/blob/main/In_class_exercise/In_class_exercise_03_10062022.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## The third In-class-exercise (10/06/2022, 40 points in total)

The purpose of this exercise is to understand text representation.

Question 1 (10 points): Describe an interesting text classification or text mining task and explain what kind of features might be useful for you to build the machine learning model. List your features and explain why these features might be helpful. You need to list at least five different types of features.

In [ ]:
# Your answer here (no code for this question, write down your answer as detail as possible for the above questions):

'''
Please write you answer here:

The features used for building an machine learning model are
Number of sentences, Number of words, Number of characters, Number of stopwords, Lower casing, Punctuation removal
This are the basic feautures which are used in building the model
these are only not enough but they play a major role in building like processing the data
I have taken some raw data for processing and explaining this function below



'''

Question 2 (20 points): Write python code to extract these features you discussed above. You can collect a few sample text data for the feature extraction.

In [2]:
# You code here (Please add comments in the code):

from six.moves import urllib
import pandas as pd

text_array = []
url = "https://raw.githubusercontent.com/Radhi1999/radhika_INFO5731_Fall2022/main/In_class_exercise/sampledata.txt"
text_file = urllib.request.urlopen(url)

for line in text_file:
  decoded_data = line.decode("utf-8").replace('\r\n', '')
  if decoded_data: text_array.append(decoded_data)
df = pd.DataFrame (text_array, columns = ['Raw Text'])
print(df)

                                              Raw Text
0                   Synonyms of about (Entry 1 of 3)\n
1                                 1having to do with\n
2    a POIGANT story about a young man who goes off...
3                                 Synonyms for about\n
4                                                   \n
..                                                 ...
117                                                 \n
118  asleep, dormant, dozing, napping, resting, sle...
119  dozy, drowsy, nodding, SLEEPY, slumberous (or ...
120                                      dreaming ME\n
121                           hypnotized, MESMERIZED\n

[122 rows x 1 columns]

In [3]:
#NUMBER OF SENTENCES

df['Number of Sentences'] = df['Raw Text'].apply(lambda x: len(str(x).split(".")))
df

                                              Raw Text  Number of Sentences
0                   Synonyms of about (Entry 1 of 3)\n                    1
1                                 1having to do with\n                    1
2    a POIGANT story about a young man who goes off...                    1
3                                 Synonyms for about\n                    1
4                                                   \n                    1
..                                                 ...                  ...
117                                                 \n                    1
118  asleep, dormant, dozing, napping, resting, sle...                    1
119  dozy, drowsy, nodding, SLEEPY, slumberous (or ...                    1
120                                      dreaming ME\n                    1
121                           hypnotized, MESMERIZED\n                    1

[122 rows x 2 columns]

In [4]:
#NUMBER OF WORDS

df['Number of Words'] = df['Raw Text'].apply(lambda x: len(str(x).split(" ")))
df

,Raw Text,Number of Sentences,Number of Words
0,Synonyms of about (Entry 1 of 3)\n,1,7
1,1having to do with\n,1,4
2,a POIGANT story about a young man who goes off...,1,12
3,Synonyms for about\n,1,3
4,\n,1,1
...,...,...,...
117,\n,1,1
118,"asleep, dormant, dozing, napping, resting, sle...",1,8
119,"dozy, drowsy, nodding, SLEEPY, slumberous (or ...",1,8
120,dreaming ME\n,1,2
121,"hypnotized, MESMERIZED\n",1,2

In [5]:
#NUMBER OF CHARACTERS

df['Number of Characters'] = df['Raw Text'].str.len()
df

,Raw Text,Number of Sentences,Number of Words,Number of Characters
0,Synonyms of about (Entry 1 of 3)\n,1,7,33
1,1having to do with\n,1,4,19
2,a POIGANT story about a young man who goes off...,1,12,54
3,Synonyms for about\n,1,3,19
4,\n,1,1,1
...,...,...,...,...
117,\n,1,1,1
118,"asleep, dormant, dozing, napping, resting, sle...",1,8,76
119,"dozy, drowsy, nodding, SLEEPY, slumberous (or ...",1,8,62
120,dreaming ME\n,1,2,12
121,"hypnotized, MESMERIZED\n",1,2,23

In [7]:
#STOPWORDS
from nltk.corpus import stopwords

import nltk
nltk.download('stopwords')
stop = stopwords.words('english')

df['Number of Stopwords'] = df['Raw Text'].apply(lambda x: len([x for x in x.split() if x in stop]))
df

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

,Raw Text,Number of Sentences,Number of Words,Number of Characters,Number of Stopwords
0,Synonyms of about (Entry 1 of 3)\n,1,7,33,3
1,1having to do with\n,1,4,19,3
2,a POIGANT story about a young man who goes off...,1,12,54,6
3,Synonyms for about\n,1,3,19,2
4,\n,1,1,1,0
...,...,...,...,...,...
117,\n,1,1,1,0
118,"asleep, dormant, dozing, napping, resting, sle...",1,8,76,0
119,"dozy, drowsy, nodding, SLEEPY, slumberous (or ...",1,8,62,0
120,dreaming ME\n,1,2,12,0
121,"hypnotized, MESMERIZED\n",1,2,23,0

In [8]:
#LOWERCASE

df['Lower Case'] = df['Raw Text'].apply(lambda x: " ".join(x.lower() for x in x.split()))
df

,Raw Text,Number of Sentences,Number of Words,Number of Characters,Number of Stopwords,Lower Case
0,Synonyms of about (Entry 1 of 3)\n,1,7,33,3,synonyms of about (entry 1 of 3)
1,1having to do with\n,1,4,19,3,1having to do with
2,a POIGANT story about a young man who goes off...,1,12,54,6,a poigant story about a young man who goes off...
3,Synonyms for about\n,1,3,19,2,synonyms for about
4,\n,1,1,1,0,
...,...,...,...,...,...,...
117,\n,1,1,1,0,
118,"asleep, dormant, dozing, napping, resting, sle...",1,8,76,0,"asleep, dormant, dozing, napping, resting, sle..."
119,"dozy, drowsy, nodding, SLEEPY, slumberous (or ...",1,8,62,0,"dozy, drowsy, nodding, sleepy, slumberous (or ..."
120,dreaming ME\n,1,2,12,0,dreaming me
121,"hypnotized, MESMERIZED\n",1,2,23,0,"hypnotized, mesmerized"

In [9]:
#REMOVAL OF PUNCTUATION
df['Removal of Punctuation'] = df['Lower Case'].str.replace('[^\w\s]','')
df

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: The default value of regex will change from True to False in a future version.

,Raw Text,Number of Sentences,Number of Words,Number of Characters,Number of Stopwords,Lower Case,Removal of Punctuation
0,Synonyms of about (Entry 1 of 3)\n,1,7,33,3,synonyms of about (entry 1 of 3),synonyms of about entry 1 of 3
1,1having to do with\n,1,4,19,3,1having to do with,1having to do with
2,a POIGANT story about a young man who goes off...,1,12,54,6,a poigant story about a young man who goes off...,a poigant story about a young man who goes off...
3,Synonyms for about\n,1,3,19,2,synonyms for about,synonyms for about
4,\n,1,1,1,0,,
...,...,...,...,...,...,...,...
117,\n,1,1,1,0,,
118,"asleep, dormant, dozing, napping, resting, sle...",1,8,76,0,"asleep, dormant, dozing, napping, resting, sle...",asleep dormant dozing napping resting sleeping...
119,"dozy, drowsy, nodding, SLEEPY, slumberous (or ...",1,8,62,0,"dozy, drowsy, nodding, sleepy, slumberous (or ...",dozy drowsy nodding sleepy slumberous or slumb...
120,dreaming ME\n,1,2,12,0,dreaming me,dreaming me
121,"hypnotized, MESMERIZED\n",1,2,23,0,"hypnotized, mesmerized",hypnotized mesmerized

Question 3 (10 points): Use any of the feature selection methods mentioned in this paper "Deng, X., Li, Y., Weng, J., & Zhang, J. (2019). Feature selection for text classification: A review. Multimedia Tools & Applications, 78(3)." Select the most important features you extracted above, rank the features based on their importance in the descending order.

In [ ]:
# You code here (Please add comments in the code):